// These styles apply to every route in the application
import Image from 'next/image';
import logo from '../../public/AdrianVeinotDark.png'
import './globals.css';
export const metadata = {
  title: 'Aaron is awesome',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-black'>

        <header className='bg-white w-screen h-50'>
          <Image src={logo} alt='logo' style={{
            maxWidth: '30%',
            height: 'auto',
          }} />
        </header>
        {children}

      </body>
    </html>
  );
}

